"""add score and findings_json to compliance_scans

Revision ID: 19516f6c8841
Revises: e84769ed1a7f
Create Date: 2026-09-07 14:38:59.134227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19516f6c8841'
down_revision = 'e84769ed1a7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliance_scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('findings_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliance_scans', schema=None) as batch_op:
        batch_op.drop_column('findings_json')
        batch_op.drop_column('score')

    # ### end Alembic commands ###
