"""add vuln scan consent field

Revision ID: 509968ca528e
Revises: 67ff7c59e696
Create Date: 2026-09-10 15:16:17.396730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509968ca528e'
down_revision = '67ff7c59e696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('founder_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vuln_scan_consent_given_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('founder_profiles', schema=None) as batch_op:
        batch_op.drop_column('vuln_scan_consent_given_at')

    # ### end Alembic commands ###
