"""add donations table and funding goal amount

Revision ID: 67ff7c59e696
Revises: 93d20783b9ab
Create Date: 2026-09-10 12:46:14.096961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ff7c59e696'
down_revision = '93d20783b9ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('founder_profile_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('supporter_name', sa.String(length=120), nullable=True),
    sa.Column('message', sa.String(length=280), nullable=True),
    sa.Column('donated_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['founder_profile_id'], ['founder_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donations_founder_profile_id'), ['founder_profile_id'], unique=False)

    with op.batch_alter_table('founder_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funding_goal_amount_cents', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('founder_profiles', schema=None) as batch_op:
        batch_op.drop_column('funding_goal_amount_cents')

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_founder_profile_id'))

    op.drop_table('donations')
    # ### end Alembic commands ###
