"""Add url reputation fields to founder profile

Revision ID: 77cd770c8cea
Revises: 509968ca528e
Create Date: 2026-09-10 15:46:10.710767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77cd770c8cea'
down_revision = '509968ca528e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('founder_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_reputation_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('url_reputation_detail', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('url_reputation_checked_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('founder_profiles', schema=None) as batch_op:
        batch_op.drop_column('url_reputation_checked_at')
        batch_op.drop_column('url_reputation_detail')
        batch_op.drop_column('url_reputation_status')

    # ### end Alembic commands ###
