"""add tier to subscriptions

Revision ID: 93d20783b9ab
Revises: 19516f6c8841
Create Date: 2026-09-07 15:23:29.300821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d20783b9ab'
down_revision = '19516f6c8841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        # server_default backfills existing rows to the base tier so no
        # subscription is left with a NULL (== no features at all) tier.
        batch_op.add_column(sa.Column('tier', sa.String(length=20), nullable=True, server_default='presentation'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('tier')

    # ### end Alembic commands ###
