"""initial schema

Revision ID: e84769ed1a7f
Revises: 
Create Date: 2026-09-07 14:27:18.588299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84769ed1a7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_de', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('legal_entity_name', sa.String(length=255), nullable=True),
    sa.Column('is_legal_entity_confirmed', sa.Boolean(), nullable=True),
    sa.Column('is_active_account', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('founder_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('tagline', sa.String(length=280), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('banner_image_path', sa.String(length=500), nullable=True),
    sa.Column('pitch_deck_path', sa.String(length=500), nullable=True),
    sa.Column('funding_goal_text', sa.String(length=300), nullable=True),
    sa.Column('donation_terms', sa.Text(), nullable=True),
    sa.Column('founder_stripe_payment_link', sa.String(length=500), nullable=True),
    sa.Column('founder_contact_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('founder_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_founder_profiles_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_founder_profiles_status'), ['status'], unique=False)

    op.create_table('chatbot_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('founder_profile_id', sa.Integer(), nullable=False),
    sa.Column('pitch_instructions', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['founder_profile_id'], ['founder_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('founder_profile_id')
    )
    op.create_table('compliance_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('founder_profile_id', sa.Integer(), nullable=False),
    sa.Column('badge_level', sa.String(length=30), nullable=True),
    sa.Column('scan_date', sa.DateTime(), nullable=True),
    sa.Column('report_path', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('requested_by_founder', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['founder_profile_id'], ['founder_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('founder_profile_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=120), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=120), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['founder_profile_id'], ['founder_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('founder_profile_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('compliance_scans')
    op.drop_table('chatbot_configs')
    with op.batch_alter_table('founder_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_founder_profiles_status'))
        batch_op.drop_index(batch_op.f('ix_founder_profiles_slug'))

    op.drop_table('founder_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
